name: 'Build and Publish Artifact'
description: 'Builds and publishes a Maven artifact'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      if: false
      
    - name: Diagnóstico de red podman
      shell: bash
      run: |
        sudo podman run --rm \
          --network=host \
          docker.io/library/bash:latest \
          bash -c '
            echo "== IP dentro del contenedor =="
            ip addr show

            sudo apt update && sudo apt install -y curl
            echo "== IP PUBLIC =="
            curl -s https://api.ipify.org


            echo "== HOSTNAME =="
            hostname
          '

