name: 'Build and Publish Artifact'
description: 'Builds and publishes a Maven artifact'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      if: false

    - name: IP Public
      shell: bash      
      run: |
          
          apt update && apt install -y curl
          echo "== IP PUBLIC =="
          curl -s https://api.ipify.org || echo "❌ No se pudo obtener la IP pública"

          echo "== HOSTNAME =="
          hostname
            
    - name: Diagnóstico de red podman
      if: false
      shell: bash
      run: |
        sudo podman run --rm \
          --network=host \
          docker.io/library/debian:latest \
          bash -c '
            apt update && apt install -y curl iproute2
    
            echo "== IP dentro del contenedor =="
            ip addr show
    
            echo "== IP PUBLIC =="
            curl -s https://api.ipify.org || echo "❌ No se pudo obtener la IP pública"
    
            echo "== HOSTNAME =="
            hostname
          '


