name: My Workflow

on:
    workflow_dispatch:
    push:
      branches:
        - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and Run Docker Compose
      run: |
        cd docker
        docker-compose build
        docker-compose up -d

    - name: ZAP Scan
      id: scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: 'http://127.0.0.1:3000/'
        
    - name: create file
      run: |
        echo "hello world" > "texto.txt"    

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: texto
        path: './texto.txt'
