name: My Workflow

on:
    workflow_dispatch:
    push:
      branches:
        - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.scan.outputs.test }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and Run Docker Compose
      run: |
        cd docker
        docker-compose build
        docker-compose up -d

    - name: ZAP Scan
      id: scan
      run: |
        { 
          docker pull ghcr.io/zaproxy/zaproxy:stable -q
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw --network=host -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://127.0.0.1:3000/ -J /zap/wrk/report_json.json -w /zap/wrk/report_md.md -r /zap/wrk/report_html.html
        } | tee /zap/wrk/scan_output.txt

    - name: Display ZAP Scan Results
      run: |
        echo "ZAP Scan Results:"
        echo "Pass Count: ${{ steps.scan.outputs.test }}
